events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # host.docker.internal перенаправляет запросы из контейнера на ваш Windows (бэкенды 5001 и 5002)
    upstream backend_nodes {
        server host.docker.internal:5001 max_fails=1 fail_timeout=5s;
        server host.docker.internal:5002 max_fails=1 fail_timeout=5s;
    }

    # Редирект HTTP -> HTTPS (301)
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # Сервер HTTPS (порт 443)
    server {
        listen 443 ssl;
        server_name localhost;

        # Сертификаты внутри контейнера
        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Фронтенд внутри контейнера
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Прокси на API
        location /api/ {
            proxy_pass http://backend_nodes;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;
            proxy_next_upstream error timeout http_502 http_503;
        }
    }
}